version: 2.1
orbs:
    gh: circleci/github-cli@1.0.3
jobs:
    build_project:
        docker:
            - image: circleci/node:12.9.1-browsers
        working_directory: ~/react-cli-templates
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Install dependencies
                  command: |
                      yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: yarn lint

    publish:
      docker:
        - image: circleci/node:12.9.1-browsers
      steps:
        - checkout
        - run:
            name: Authenticate with registry
            command: |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @pxblue/cra-template-blank
            command:  |
              cd blank && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/cra-template-blank-typescript
            command:   |
              cd blank-typescript && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/cra-template-routing
            command:  |
              cd routing && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/cra-template-routing-typescript
            command:   |
              cd routing-typescript && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/cra-template-authentication
            command:  |
              cd authentication && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/cra-template-routing-authentication-typescript
            command:   |
              cd authentication-typescript && yarn publish:package -b $CIRCLE_BRANCH

    tag:
      docker:
        - image: circleci/node:12.9.1-browsers
      steps:
        - checkout
        - gh/setup
        - run:
            name: Tag @pxblue/cra-template-blank
            command:  |
              cd blank && yarn tag:package -b $CIRCLE_BRANCH
        - run:
            name: Tag @pxblue/cra-template-blank-typescript
            command:   |
              cd blank-typescript && yarn tag:package -b $CIRCLE_BRANCH
        - run:
            name: Tag @pxblue/cra-template-routing
            command:  |
              cd routing && yarn tag:package -b $CIRCLE_BRANCH
        - run:
            name: Tag @pxblue/cra-template-routing-typescript
            command:   |
              cd routing-typescript && yarn tag:package -b $CIRCLE_BRANCH
        - run:
            name: Tag @pxblue/cra-template-authentication
            command:  |
              cd authentication && yarn tag:package -b $CIRCLE_BRANCH
        - run:
            name: Tag @pxblue/cra-template-routing-authentication-typescript
            command:   |
              cd authentication-typescript && yarn tag:package -b $CIRCLE_BRANCH

workflows:
    version: 2
    react-cli-templates:
        jobs:
            - build_project
            - publish:
                requires:
                    - build_project
                filters:
                    branches:
                        only:
                            - master
                            - dev
            - tag:
                requires:
                  - publish
                filters:
                  branches:
                    only:
                      - master
